package com.simpleworkshopsoftware.dto;

import com.simpleworkshopsoftware.entities.Car;
import com.simpleworkshopsoftware.entities.Customer;
import com.simpleworkshopsoftware.entities.WorkOrder;
import com.simpleworkshopsoftware.pdfGenerator.PdfService;

import java.util.List;
/**
 * This class gathers data from customer, car, and work order entities,
 * along with additional information generated by the PdfService class,
 * to be used for creating a comprehensive PDF document.
 *
 * @author Attila Eckert
 * @date 12/27/2024
 * @version 1.0
 */
public class PdfDTO {
    private final String compName;
    private final String compInformation;
    private final String customerInformation;
    private final String carModel;
    private final String carInformation;
    private final String issueOrRepair;
    private final String expectedOrNextRepairs;
    private final String discountPercent;
    private final String partsCost;
    private final String laborCost;
    private final String overallCost;
    private final String withoutTax;
    private final String date;
    private final String expectedDate;
    private final String title;
    private final String documentNumber;
    private final String note;
    private final String footerNote;
    private final String filePath;
    private final List<String[]> workTableData;
    private final List<String[]> partsTableData;
    private final boolean isWorkOrder;

    public PdfDTO(Customer cust, Car car, WorkOrder wo) {
        PdfService service = new PdfService();
        this.compName = service.getCompanyName();
        this.compInformation = service.getCompanyDetails();
        this.isWorkOrder = wo.isClosed();
        this.documentNumber = wo.getTitle();
        this.customerInformation = service.getCustomerInformation(cust);
        this.carModel = service.getCarModel(car);
        this.carInformation = service.getCarInformation(car);
        this.note = service.getNoteFromWorkOrder(wo);
        this.date = service.getDateFromWorkOrder(wo);
        this.expectedDate = service.getExpectedDateFromWorkOrder(wo);
        this.discountPercent = service.getDiscountFromWorkOrder(wo);
        this.partsCost = service.getPartsCostFromWorkOrder(wo);
        this.laborCost = service.getLaborCostFromWorkOrder(wo);
        this.overallCost = service.getOverallCostFromWorkOrder(wo);
        this.withoutTax = service.getWithoutTaxFromWorkOrder(wo);
        this.title = service.getTitleFromWorkOrder(wo);
            this.issueOrRepair = service.getIssueOrRepairFromWorkOrder(wo);
            this.expectedOrNextRepairs = service.getExpectedOrNextRepairsFromWorkOrder(wo);
        service.setTableInformation(wo);
        this.footerNote = service.getTailText();
        this.filePath = service.getFilePath(documentNumber);
        this.workTableData = service.getWorkTableData(wo);
        this.partsTableData = service.getPartsTableData(wo);
    }

    public String getCompName() {
        return compName;
    }

    public String getCompInformation() {
        return compInformation;
    }

    public String getCustomerInformation() {
        return customerInformation;
    }

    public String getCarModel() {
        return carModel;
    }

    public String getCarInformation() {
        return carInformation;
    }

    public String getIssueOrRepair() {
        return issueOrRepair;
    }

    public String getExpectedOrNextRepairs() { return expectedOrNextRepairs; }

    public String getDiscountPercent() {
        return discountPercent;
    }

    public String getPartsCost() {
        return partsCost;
    }

    public String getLaborCost() {
        return laborCost;
    }

    public String getOverallCost() {
        return overallCost;
    }

    public String getWithoutTax() {
        return withoutTax;
    }

    public String getDate() {
        return date;
    }

    public String getExpectedDate() {return expectedDate;}

    public String getTitle() {
        return title;
    }

    public String getDocumentNumber() {
        return documentNumber;
    }

    public String getNote() {
        return note;
    }

    public String getFooterNote() { return footerNote; }

    public String getFilePath() { return filePath; }

    public List<String[]> getWorkTableData() {
        return workTableData;
    }

    public List<String[]> getPartsTableData() {
        return partsTableData;
    }

    public boolean isWorkOrder() {
        return isWorkOrder;
    }
}
